# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'SlideInTransition' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SlideInTransition
pod 'ExpandingMenu', '~> 0.4'
pod 'FSCalendar'
pod 'PopupDialog', '~> 1.1'
end
